[package]
name = "rooms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra-glm = "0.18.0"
rand = "0.8.5"
rust-raylib = "0.45.11"
trustme = "1.0.1"
